version: '3.7'
services:
  postgres:
    image: 'postgres:11-alpine'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres

  web:
    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      - postgres
    environment:
      APPSIGNAL_BUILD_FOR_MUSL: 1
      PGUSER: "postgres"
      PGPASS: "postgres"
      PGHOST: "postgres"
      PGPORT: "5432"
    ports:
      - '4000:4000'
    volumes:
      - .:/app
    links:
      - postgres
